name: Ruby CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: password
        ports: ['5432:5432']

    strategy:
      matrix:
        ruby-version: ['3.2.1' ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install dependencies
        run: bundle install
      - name: Setup Database
        env:
          POSTGRES_DATABASE: postgres
          POSTGRES_HOST: localhost
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          RAILS_ENV: test
          WITH_COVERAGE: true
          DISABLE_SPRING: 1
          RAILS_MASTER_KEY: 0d1d5b904eef593a1b194dbcf7bb64a7
        run: |
          bundle exec rails db:prepare
          bundle exec rake test
          
  docker-release:
    name: Tagged Docker release to Google Artifact Registry
    runs-on: ubuntu-latest
    outputs:
      current_image: ${{ steps.get-tag.outputs.short_ref }}
    needs: test
    #    if: github.event_name == 'push' && startsWith(github.ref, 'main')  # <-- Notice that I'm filtering here to only run when a tagged commit is pushed

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2

      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0
        with:
          token_format: access_token
          workload_identity_provider: projects/222622094445/locations/global/workloadIdentityPools/my-pool/providers/my-provider
          service_account: gha-service-account@inputhealth-chr-dev.iam.gserviceaccount.com
          access_token_lifetime: 300s

      - name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: northamerica-northeast1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Get tag
        id: get-tag
#        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}
        run: echo "short_ref=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - id: docker-push-tagged
        name: Tag Docker image and push to Google Artifact Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            northamerica-northeast1-docker.pkg.dev/inputhealth-chr-dev/ops-demo/friends-api:${{ steps.get-tag.outputs.short_ref }}
            northamerica-northeast1-docker.pkg.dev/inputhealth-chr-dev/ops-demo/friends-api:latest

  cd-prep:
    needs: docker-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Test fetch image tag
        with:
          repository: profemzy/argocd-gitops
      - name: modify-image
        run: |
          git config user.email profemzy@gmail.com
          git config user.name Femi
          cd helm-charts/friends-api
          cat values.yaml
          sed -i 's/latest/${{ needs.docker-release.outputs.current_image }}/g' values.yaml
          cat values.yaml